const countries = [
  { code: '+964', name: 'العراق', flag: '🇮🇶', currency: 'IQD' },
  { code: '+963', name: 'سوريا', flag: '🇸🇾', currency: 'SYP' },
  { code: '+966', name: 'السعودية', flag: '🇸🇦', currency: 'SAR' },
  { code: '+971', name: 'الإمارات', flag: '🇦🇪', currency: 'AED' },
  { code: '+974', name: 'قطر', flag: '🇶🇦', currency: 'QAR' },
  { code: '+973', name: 'البحرين', flag: '🇧🇭', currency: 'BHD' },
  { code: '+965', name: 'الكويت', flag: '🇰🇼', currency: 'KWD' },
  { code: '+968', name: 'عمان', flag: '🇴🇲', currency: 'OMR' },
  { code: '+962', name: 'الأردن', flag: '🇯🇴', currency: 'JOD' },
  { code: '+20', name: 'مصر', flag: '🇪🇬', currency: 'EGP' },
  { code: '+216', name: 'تونس', flag: '🇹🇳', currency: 'TND' },
  { code: '+213', name: 'الجزائر', flag: '🇩🇿', currency: 'DZD' },
  { code: '+212', name: 'المغرب', flag: '🇲🇦', currency: 'MAD' },
  { code: '+218', name: 'ليبيا', flag: '🇱🇾', currency: 'LYD' },
  { code: '+249', name: 'السودان', flag: '🇸🇩', currency: 'SDG' },
  { code: '+967', name: 'اليمن', flag: '🇾🇪', currency: 'YER' },
  { code: '+970', name: 'فلسطين', flag: '🇵🇸', currency: 'ILS' },
  { code: '+961', name: 'لبنان', flag: '🇱🇧', currency: 'LBP' },
  { code: '+1', name: 'الولايات المتحدة', flag: '🇺🇸', currency: 'USD' },
  { code: '+44', name: 'المملكة المتحدة', flag: '🇬🇧', currency: 'GBP' },
  { code: '+49', name: 'ألمانيا', flag: '🇩🇪', currency: 'EUR' },
  { code: '+33', name: 'فرنسا', flag: '🇫🇷', currency: 'EUR' },
  { code: '+90', name: 'تركيا', flag: '🇹🇷', currency: 'TRY' },
  { code: '+91', name: 'الهند', flag: '🇮🇳', currency: 'INR' },
  { code: '+86', name: 'الصين', flag: '🇨🇳', currency: 'CNY' },
];

module.exports = countries;
